name: Docker
description: Runs your build steps in Docker containers
author: https://github.com/buildkite
requirements:
  - docker
configuration:
  properties:
    additional-groups:
      type: array
    always-pull:
      type: boolean
    command:
      type: array
    debug:
      type: boolean
    entrypoint:
      type: [string, boolean]
    environment:
      type: array
    image:
      type: string
    mount-buildkite-agent:
      type: boolean
    mount-ssh-agent:
      type: boolean
    mount-checkout:
      type: boolean
    network:
      type: string
    runtime:
      type: string
    shell:
      type: [boolean, array]
    shm-size:
      type: string
    tty:
      type: boolean
    user:
      type: string
    volumes:
      type: array
    tmpfs:
      type: array
    workdir:
      type: string
    capabilities:
        type: array
    propagate-environment:
      type: boolean
    propagate-uid-gid:
      type: boolean
    privileged:
      type: boolean
    init:
      type: boolean
    sysctls:
      type: array
  required:
    - image
  additionalProperties: false
